steps:
  - name: maven:3.9-eclipse-temurin-20
    entrypoint: mvn
    args: ['install -pl plugins/templates-maven-plugin -am']
  - name: maven:3.9-eclipse-temurin-20
    entrypoint: mvn
    args: 
      - 'package'
      - '-PtemplateStage' 
      - '-DskipTests'
      - '-DprojectId="${_TARGET_PROJECT}"'
      - '-DbucketName="${_TARGET_BUCKET_NAME}"'
      - '-DstagePrefix="images/$(date +%Y_%m_%d-%H_%M_)"'
      - '-DtemplateName="Cloud_Datastream_to_BigQuery"'
      - '-pl=v2/datastream-to-bigquery'
      - '-am'